#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-globalkeys
Version  : 1.1.0
Release  : 16
URL      : https://github.com/lxqt/lxqt-globalkeys/releases/download/1.1.0/lxqt-globalkeys-1.1.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-globalkeys/releases/download/1.1.0/lxqt-globalkeys-1.1.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-globalkeys/releases/download/1.1.0/lxqt-globalkeys-1.1.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: lxqt-globalkeys-bin = %{version}-%{release}
Requires: lxqt-globalkeys-data = %{version}-%{release}
Requires: lxqt-globalkeys-lib = %{version}-%{release}
Requires: lxqt-globalkeys-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kwindowsystem-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools
BuildRequires : qtbase-dev
BuildRequires : qttools-dev

%description
# lxqt-globalkeys
## Overview
This repository is providing tools to set global keyboard shortcuts in LXQt
sessions, that is shortcuts which apply to the LXQt session as a whole and are
not limited to distinct applications.

%package bin
Summary: bin components for the lxqt-globalkeys package.
Group: Binaries
Requires: lxqt-globalkeys-data = %{version}-%{release}
Requires: lxqt-globalkeys-license = %{version}-%{release}

%description bin
bin components for the lxqt-globalkeys package.


%package data
Summary: data components for the lxqt-globalkeys package.
Group: Data

%description data
data components for the lxqt-globalkeys package.


%package dev
Summary: dev components for the lxqt-globalkeys package.
Group: Development
Requires: lxqt-globalkeys-lib = %{version}-%{release}
Requires: lxqt-globalkeys-bin = %{version}-%{release}
Requires: lxqt-globalkeys-data = %{version}-%{release}
Provides: lxqt-globalkeys-devel = %{version}-%{release}
Requires: lxqt-globalkeys = %{version}-%{release}

%description dev
dev components for the lxqt-globalkeys package.


%package lib
Summary: lib components for the lxqt-globalkeys package.
Group: Libraries
Requires: lxqt-globalkeys-data = %{version}-%{release}
Requires: lxqt-globalkeys-license = %{version}-%{release}

%description lib
lib components for the lxqt-globalkeys package.


%package license
Summary: license components for the lxqt-globalkeys package.
Group: Default

%description license
license components for the lxqt-globalkeys package.


%prep
%setup -q -n lxqt-globalkeys-1.1.0
cd %{_builddir}/lxqt-globalkeys-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650311672
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1650311672
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-globalkeys
cp %{_builddir}/lxqt-globalkeys-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-globalkeys/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lxqt-config-globalkeyshortcuts
/usr/bin/lxqt-globalkeysd

%files data
%defattr(-,root,root,-)
/usr/share/applications/lxqt-config-globalkeyshortcuts.desktop
/usr/share/lxqt/globalkeyshortcuts.conf
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ar.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_arn.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ast.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_bg.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ca.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_cs.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_cy.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_da.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_de.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_el.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_en_GB.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_eo.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_es.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_es_VE.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_et.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_eu.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_fi.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_fr.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_gl.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_he.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_hr.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_hu.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_id.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_it.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ja.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ko.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_lt.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_lv.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_nb_NO.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_nl.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_pl.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_pt.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_pt_BR.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ro_RO.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_ru.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_si.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_sk_SK.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_sl.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_th_TH.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_tr.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_uk.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_zh_CN.qm
/usr/share/lxqt/translations/lxqt-config-globalkeyshortcuts/lxqt-config-globalkeyshortcuts_zh_TW.qm

%files dev
%defattr(-,root,root,-)
/usr/include/lxqt-globalkeys-ui/LXQtGlobalKeysUi/ShortcutSelector
/usr/include/lxqt-globalkeys-ui/shortcut_selector.h
/usr/include/lxqt-globalkeys-ui/shortcutselector.h
/usr/include/lxqt-globalkeys/LXQtGlobalKeys/Action
/usr/include/lxqt-globalkeys/LXQtGlobalKeys/Client
/usr/include/lxqt-globalkeys/LXQtGlobalKeys/LXQtGlobalKeys
/usr/include/lxqt-globalkeys/action.h
/usr/include/lxqt-globalkeys/client.h
/usr/include/lxqt-globalkeys/lxqt-globalkeys.h
/usr/include/lxqt-globalkeys/lxqtglobalkeys.h
/usr/lib64/liblxqt-globalkeys-ui.so
/usr/lib64/liblxqt-globalkeys.so
/usr/lib64/pkgconfig/lxqt-globalkeys-ui.pc
/usr/lib64/pkgconfig/lxqt-globalkeys.pc
/usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-config-version.cmake
/usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-config.cmake
/usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-targets-relwithdebinfo.cmake
/usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-targets.cmake
/usr/share/cmake/lxqt-globalkeys/lxqt-globalkeys-config-version.cmake
/usr/share/cmake/lxqt-globalkeys/lxqt-globalkeys-config.cmake
/usr/share/cmake/lxqt-globalkeys/lxqt-globalkeys-targets-relwithdebinfo.cmake
/usr/share/cmake/lxqt-globalkeys/lxqt-globalkeys-targets.cmake

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblxqt-globalkeys-ui.so.1
/usr/lib64/liblxqt-globalkeys-ui.so.1.1.0
/usr/lib64/liblxqt-globalkeys.so.1
/usr/lib64/liblxqt-globalkeys.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lxqt-globalkeys/7fab4cd4eb7f499d60fe183607f046484acd6e2d
